# Generated by Django 2.2.6 on 2019-11-14 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_auto_20191114_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(related_name='quotes', to='quotes_app.User'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='quotes_app.User'),
        ),
    ]
